### ISSUE TITLE
Intermittent AWS forbidden error

### ISSUE THREAD

**Issue by ericandrewlewis** [newsdev/assets-deploy#1]
I get an intermittent generic forbidden error when running the deploy.

```
/usr/local/bundle/gems/aws-sdk-core-2.0.28/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Aws::S3::Errors::Forbidden
	from /usr/local/bundle/gems/aws-sdk-core-2.0.28/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:18:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.0.28/lib/seahorse/client/plugins/param_conversion.rb:22:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.0.28/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.0.28/lib/seahorse/client/plugins/response_target.rb:18:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.0.28/lib/seahorse/client/request.rb:70:in `send_request'
	from /usr/local/bundle/gems/aws-sdk-core-2.0.28/lib/seahorse/client/base.rb:216:in `block (2 levels) in define_operation_methods'
	from /usr/local/bin/assets-deploy:52:in `exists?'
	from /usr/local/bin/assets-deploy:99:in `block (2 levels) in <main>'
```

**Comment by ericandrewlewis** [comment]
This was an IAM S3 permissions error. Added better error messages in https://github.com/newsdev/assets-deploy/commit/446621a86d6b33cc1253851e7c5151f0212c4278.
